// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsiafoosbmsndhiuppzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzaWFmb29zYm1zbmRoaXVwcHp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODcxMDksImV4cCI6MjA3MjY2MzEwOX0.kaM5-qTPHcpGYid2_PV50fWPeNZs6o4IfkCTurp7R6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});